name: Run automated tests

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - uses: fabriciomurta/ensure-nuget-source@v1
      with:
        name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'
    - name: Clean project
      run: dotnet clean
    - name: Install dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release --no-restore
    - name: Run unit tests
      run: dotnet test --no-restore --verbosity normal
    # - name: Build integration test project
    #   run: dotnet build tests/Mollie.Tests.Integration --configuration Release --no-restore
    # - name: Run integration tests
    #   run: dotnet test tests/Mollie.Tests.Integration --filter "TestCategory!=AccessKeyIntegrationTest" --no-restore --verbosity normal 
    #   env:
    #     Mollie__ApiKey: ${{ secrets.Mollie__ApiKey }}
    #     Mollie__AccessKey: ${{ secrets.Mollie__AccessKey }}
    #     Mollie__ClientId: ${{ secrets.Mollie__ClientId }}
    #     Mollie__ClientSecret: ${{ secrets.Mollie__ClientSecret }}
