name: Run automated tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup NuGet Client
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest

    - name:
      run: dotnet nuget locals --clear all

    - name: Install dependencies
      run: dotnet restore

    - name: Build unit test project
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test tests/Mollie.Tests.Unit --no-restore --verbosity normal

    # - name: Build integration test project
    #   run: dotnet build tests/Mollie.Tests.Integration --configuration Release --no-restore

    # - name: Run integration tests
    #   run: dotnet test tests/Mollie.Tests.Integration --filter "TestCategory!=AccessKeyIntegrationTest" --no-restore --verbosity normal 
    #   env:
    #     Mollie__ApiKey: ${{ secrets.Mollie__ApiKey }}
    #     Mollie__AccessKey: ${{ secrets.Mollie__AccessKey }}
    #     Mollie__ClientId: ${{ secrets.Mollie__ClientId }}
    #     Mollie__ClientSecret: ${{ secrets.Mollie__ClientSecret }}